### ISSUE TITLE
Sanitizing filenames

### ISSUE THREAD

**Issue by bjoerns1983** [fnep/mtv_dl#12]
Hi there,
i just wanted to know if it would be possible to add an option or if it would be generally a good idea to sanitize the filesnames generated by mtv_dl.

For example when i download the current Mord auf Shetland Episodes there is a | added to the filename which makes problems when you try to transfer the file via scp or SMB.
Same problem when there is a : in the filename etc.

**Comment by fnep** [comment]
Ok this should get fixed in general. 

There is already a handling of invalid characters, but this is checking for the operating system (on Windows these characters would be replaced with '_'). 

I should probably change to always replace these characters instead. I will put it on my todo list for the weekend. :)

**Comment by fnep** [comment]
Should be solved in v0.13 (now on pypi).
