### ISSUE TITLE
channel doesnt work in --target=<path>

### ISSUE THREAD

**Issue by elschman** [fnep/mtv_dl#94]
I used 
mtv_dl download  -h topic="Tatort"  title!=Audiodeskription title!=Gebärdensprache title!=Untertitel --series duration+60m -t "/nfs/video/serien/Tatort/S{season}E{episode} - {title} - ${channel} {hash}{ext}"
So the target file name should contain the channel name but I only see title followed by hash
'S00E00 - Tatort_ Wie einst Lilly -  db0bb9f234d8d39b108f9ec20d80fc6c546b0155.mp4'
obviously channel isnt used for naming

**Comment by fnep** [comment]
Do you really want to have this "$" in your file name? I would assume you are on a Linux or Mac system with a bash or another compatible shell.

The name pattern is in `"` and so if you use `${channel}` the shell will replace it with the content of the environment variable 'channel' instead of giving it to mtv-dl.

Would you try removing the `$` OR use `'` as quotation mark?

- `-t "/nfs/video/serien/Tatort/S{season}E{episode} - {title} - {channel} {hash}{ext}"`
- `-t '/nfs/video/serien/Tatort/S{season}E{episode} - {title} - ${channel} {hash}{ext}'`

**Comment by elschman** [comment]
OMG 8-) ! You are so right ! Sorry to bother you .

**Comment by elschman** [comment]
I was so blind

**Comment by fnep** [comment]
Dont worry. Happy if it works for you.
